div(id = "gc2dapp", column(width = 12,
                         mainPanel(width = 12, 
                                   div(class="maincontent",
                                       HTML("<h2>2D-GCxGC mode</h2>"),
                                       HTML("<p>In 2D GCxGC mode, two peak detection methods, msPeak-NEB and msPeakG-Del1, and two peak alignment methods, mSPA and eRah-align, are available for running.</p>
                          <hr>")
                                   )
                                   
                         ),
       sidebarPanel(width = 4,
                    titlePanel("Parameter configuration"),
                    fluidRow(
                      column(8, h5("Input_path"),
                             actionButton("Input_path","Select folder"),
                             div(class="mt-n45", textInput("Input_path_txt", "", value="/var/log/shiny-server/INPUT", placeholder = "No directory has been selected"))),
                      column(4, radioButtons("Input_file", h5("Input_file"),
                                             c("*.cdf" = "cdf$",
                                               "Choice 2" = "choice2",
                                               "Choice 3" = "choice3")))),
                    fluidRow(column(8, h5("Output_folder"),
                                    actionButton("Output_folder","Select folder"),
                                    div(class="mt-n45", textInput("output_folder_txt", "",value="/var/log/shiny-server/OUTPUT", placeholder = "No directory has been selected")))),                    
                    fluidRow(
                      column(12, h3("Peak detection")),
                      column(12,
                             checkboxInput("do_peak_detection", "do_peak_detection", value = TRUE)),
                      column(12, selectInput("method_peak_gc2d", h5("method"), 
                                         choices = list("NEB" = "NEB", "fft" = "fft", "delta1" = "delta1", "delta2" = "delta2"))),
                      column(12, h5("TIC reference"),
                                 actionButton("reference","Select folder"),
                                 div(class="mt-n45", textInput("reference_gc2d", "",value="NULL", placeholder = "No directory has been selected")))),                      
                    fluidRow(
                      column(3,
                             numericInput("worker",
                                          h5("worker"),
                                          value = 14)),
                      column(3,
                             numericInput("method_parallel",
                                          h5("method_parallel"),
                                          value = 2)),
                      column(3,
                             numericInput("zcv",
                                          h5("zcv"),
                                          value = 0.3, step = 0.1)),
                      column(3,
                             numericInput("cv",
                                          h5("cv"),
                                          value = 0.95, step = 0.1)), 
                      column(3,
                             numericInput("modulation_time",
                                          h5("modulation_time"),
                                          value = 4)),
                      column(3,
                             numericInput("sampling_rate",
                                          h5("sampling_rate"),
                                          value = FALSE)),     
                      column(6, selectInput("profMat_method", h5("profMat_method"), 
                                         choices = list("binlin" = "binlin", "bin" = "bin"))),
                      column(6,
                             numericInput("profMat_step",
                                          h5("profMat_step"),
                                          value = 1.0)),
                      column(3,
                             checkboxInput("rm_prev_tic", "rm_prev_tic", value = TRUE)),
                      column(3,
                             checkboxInput("full_scan", "full_scan", value = FALSE)),
                      column(3,
                            checkboxInput("peak_merge", "peak_merge", value = TRUE))),                   
                    fluidRow(
                      column(12, h5("Peak time_scan:")),
                      column(3,
                             numericInput("RT1Dstart",
                                          h5("RT1Dstart"),
                                          value = 10)),
                      column(3,
                             numericInput("RT1Dstop",
                                          h5("RT1Dstop"),
                                          value = 15)),
                      column(3,
                             numericInput("RT2Dstart",
                                          h5("RT2Dstart"),
                                          value = 0.1, step = 0.1)),
                      column(3,
                             numericInput("RT2Dstop",
                                          h5("RT2Dstop"),
                                          value = 5))),
                    fluidRow(
                      column(12, h3("Peak alignment")),
                      column(6,
                             checkboxInput("do_peak_alignment", "do_peak_alignment", value = TRUE)),
                      column(12, h5("reference"),
                                   actionButton("reference","Select folder"),
                                   div(class="mt-n45", textInput("reference_align_gc2d", "",value="NULL", placeholder = "No directory has been selected"))),
                      column(12, selectInput("method_align_gc2d", h5("select peak alignment method"), 
                                         choices = list("mSPA" = "mSPA", "ERah-align" = "ERah")))),                                  
                    fluidRow(
                      column(12, h4("mSPA alignment parameters")),
                      column(12, h5("reference"),
                                   actionButton("reference","Select folder"),
                                   div(class="mt-n45", textInput("reference_gc2d", "",value="NULL", placeholder = "No directory has been selected"))),

                      column(12, selectInput("mSPA_method", h5("mSPA alignment methhod"), 
                                   choices = list("PAD" = "PAD", "PAS" = "PAS","DW-PAS" = "DW-PAS","SW-PAD" = "SW-PAD","PAM" = "PAM","OP-PAM" = "OP-PAM"))),
                                                                     
                      column(3, numericInput("mSPA_w", 
                                          h5("w"), 
                                          value = 0.5, step = 0.1)),                                         
                      column(3, numericInput("mSPA_k", 
                                          h5("k"), 
                                          value = 5, step = 0.1)),    
                      column(3, numericInput("mSPA_rho", 
                                          h5("rho"), 
                                          value = 0.95, step = 0.01)),  
                      column(3, numericInput("mSPA_sd1Thres", 
                                          h5("sd1Thres"), 
                                          value = 25.0, step = 0.1)),      
                      column(3, numericInput("mSPA_sd2Thres", 
                                          h5("sd2Thres"), 
                                          value = 0.05, step = 0.01)),   
		      column(12, selectInput("mSPA_distance", h5("Distance"), 
                                   choices = list("canberra" = "canberra", "maximum" = "maximum","manhattan" = "manhattan","euclidean" = "euclidean"))),   
                      column(12, selectInput("mSPA_arraySimilarity", h5("arraySimilarity"), 
                                   choices = list("dot" = "dot", "pearson" = "pearson"))), 
                                   
                      column(4,
                             checkboxInput("mSPA_createReferenceAlignment", "createReferenceAlignment", value = FALSE)),
                      column(12, selectInput("mSPA_referenceAlignmentVariant", h5("referenceAlignmentVariant"), 
                                   choices = list("mSPA" = "mSPA", "mgma" = "mgma")))),  
                    fluidRow(
                      column(12, h4("ERah alignment parameters")),
                      column(3, numericInput("ERah_min.spectra.cor", 
                                          h5("min.spectra.cor"), 
                                          value = 0.85, step = 0.01)),   
                      column(3, numericInput("ERah_max.time.dist", 
                                          h5("max.time.dist"), 
                                          value = 1, step = 0.1))),                                            
                                   

                    fluidRow(
                      column(12, h3("Peak annotation")),
                      column(12,
                             checkboxInput("do_peak_annotation", "do_peak_annotation", value = TRUE)),
                      column(4, 
                             numericInput("MinInt", 
                                          h5("MinInt"), 
                                          value = 20)),
                      column(4, 
                             numericInput("MinMF", 
                                          h5("MinMF"), 
                                          value = 700)),
                      column(4, 
                             numericInput("HITS", 
                                          h5("HITS"), 
                                          value = 10, step = 0.1))),
                    fluidRow(
                      column(8, h5("path_MSPepSearch"),
                             actionButton("path_MSPepSearch","Select folder"),
                             div(class="mt-n45", textInput("path_MSPepSearch_txt", "", value="/2019_02_22_MSPepSearch_x32/MSPepSearch.exe", placeholder = "../2019_02_22_MSPepSearch_x64/"))),
                      column(8, h5("path_MAIN"),
                             actionButton("path_MAIN","Select folder"),
                             div(class="mt-n45", textInput("path_MAIN_txt", "", value="/var/log/shiny-server/NIST_library/mainlib", placeholder = "../NIST_library/mainlib"))),
                      column(8, h5("path_REPL"),
                             actionButton("path_REPL","Select folder"),
                             div(class="mt-n45", textInput("path_REPL_txt", "", value="/var/log/shiny-server/NIST_library/replib", placeholder = "../NIST_library/replib")))),  
                             
                    fluidRow(
                            column(12, h3("Peak summary")),
                            column(12,
                                   checkboxInput("do_peak_summary", "do_peak_summary", value = TRUE)),
                            column(4, selectInput("select_name", h5("select_name"), 
                                                  choices = list("by_consensus" = "by_consensus", "by_MF" = "by_MF"))),                                   
                            column(8, h5("reference"),
                                   actionButton("reference","Select folder"),
                                   div(class="mt-n45", textInput("reference_sum", "",value="NULL", placeholder = "No directory has been selected")))),                             
                                               
                    fluidRow(
                      column(12, hr(class="lightcol"), div(class="text-right",
                                     actionButton("apply_gc2d", "Generate configuration file"),
                                     actionButton("reset", "Reset"))))
       ),
       mainPanel(width = 8, h2("Output"),
                   div(id = "summary_box",verbatimTextOutput("summary", placeholder = TRUE)),
                 hidden(div(id = "graph_box",plotlyOutput("graph"))),
                 hidden(div(id = "coord_box",br(),verbatimTextOutput("coord_out"))),
                 div(id = "heatmap_box", 
                            fluidRow(plotlyOutput("heatmap", height = "800px"),
                                     hr(),dataTableOutput("heatmaptb"))
                 ),
                 br(),
                 div(class="text-right",
                     disabled(actionButton("proceed_gc2d", "Proceed")),
                     disabled(actionButton("submit_gc2d", "Submit job"))),
                 hidden(
                   div(id = "downloadgc2d_btn",
                       fluidRow(
                         column(12, hr()),
                         column(12, downloadButton("download_gc2d", "Download output"), actionButton("view_alignment", "View alignment"))
                       )
                   )
                 )
                 
       )
))
