div(id = "gcapp", column(width = 12,
       mainPanel(width = 12, 
                 div(class="maincontent",
                     HTML("<h2>1D-GC mode</h2>"),
                     HTML("<p>In 1D GC mode, three peak detection algorithms, MatchedFiltered, CentWave and eRah-peak, and two peak alignment algorithms, GCalignR, and eRah-align, are available. </p>
                          <hr>")
                 )
                 
       ),
       sidebarPanel(width = 4,
                    titlePanel("Parameter configuration"),
                    fluidRow(
                            column(8, h5("Input_path"),
                                   actionButton("Input_path","Select folder"),
                                   div(class="mt-n45", textInput("Input_path_txt", "", value="/var/log/shiny-server/INPUT", placeholder = "No directory has been selected"))),
                            column(4, radioButtons("Input_file", h5("Input_file"),
                                                   c("*.cdf" = "*.cdf",
                                                     "Choice 2" = "choice2",
                                                     "Choice 3" = "choice3")))),
                    fluidRow(column(8, h5("Output_folder"),
                                    actionButton("Output_folder","Select folder"),
                                    div(class="mt-n45", textInput("output_folder_txt", "",value="/var/log/shiny-server/OUTPUT", placeholder = "No directory has been selected")))),
                    fluidRow(
                            column(12, h3("Peak detection")),

                            column(12,
                                   checkboxInput("do_peak_detection", "do_peak_detection", value = TRUE)),                                  
                                                      
                            column(4, selectInput("method_peak_gc", h5("method"), 
                                                  choices = list("centWave" = "centWave", "matchedFilter" = "matchedFilter", "ERah" = "ERah"))),
                             column(4, 
                                    numericInput("worker", 
                                                 h5("worker"), 
                                                 value = 4)),
                             column(4, 
                                    numericInput("CAMERA_perfwhm", 
                                                 h5("CAMERA_perfwhm"), 
                                                 value = 1)),
                             column(4, 
                                    checkboxInput("to2D", "to2D", value = FALSE)),
                             column(4, 
                                    numericInput("to2Dmodulation_time", 
                                                 h5("modulation_time"), 
                                                 value = 4))),                          
                    fluidRow(
                             column(12, h4("centWave Parameters")),
                             column(4, 
                                   numericInput("peakwidth_min", 
                                                h5("peakwidth_min"), 
                                                value = 5)),
                             column(4, 
                                    numericInput("peakwidth_max", 
                                                 h5("peakwidth_max"), 
                                                 value = 10))),
                    fluidRow(
                            column(4,  
                                   numericInput("ppm", 
                                                h5("ppm"),
                                                value = 20)), 
                            column(4,  
                                   numericInput("snthresh", 
                                                h5("snthresh"),
                                                value = 10))),
                    fluidRow(
                             column(12, h4("matchedFilter Parameters")),
                             column(4, 
                                   numericInput("snthresh", 
                                                h5("snthresh"), 
                                                value = 20)),
                             column(4, 
                                    numericInput("fwhm", 
                                                 h5("fwhm"), 
                                                 value = 3))),
                    fluidRow(column(4, 
                                    numericInput("step", 
                                                 h5("step"), 
                                                 value = 0.5)),
                            column(4,  
                                   numericInput("steps", 
                                                h5("steps"), 
                                                value = 2))),
                    fluidRow(column(4, 
                                    numericInput("mzdiff", 
                                                 h5("mzdiff"), 
                                                 value = 0)),
                            column(4,  
                                   numericInput("max", 
                                                h5("max"), 
                                                value = 500))),
                    fluidRow(
                             column(12, h4("ERah Parameters")),
                             column(4, 
                                   numericInput("noise.threshold", 
                                                h5("noise.threshold"), 
                                                value = 20)),
                             column(4, 
                                    numericInput("min.peak.height", 
                                                 h5("min.peak.height"), 
                                                 value = 500))),
                    fluidRow(column(4, 
                                    numericInput("min.peak.width", 
                                                 h5("min.peak.width"), 
                                                 value = 0.7))),                                                                         
                    fluidRow(
                            column(12, h3("Peak alignment")),
                            column(12,
                                   checkboxInput("do_peak_alignment", "do_peak_alignment", value = TRUE)),
                            column(4, selectInput("method_align_gc", h5("method"), 
                                                  choices = list("ERah" = "ERah", "GCalignR" = "GCalignR"))),
                                                            
                            column(8, h5("reference"),
                                   actionButton("reference","Select folder"),
                                   div(class="mt-n45", textInput("reference_txt", "",value="NULL", placeholder = "No directory has been selected")))),
                                   
                    fluidRow(
                    	     column(12, h4("GCalignR alignment parameters")),
                            column(4, 
                                   numericInput("max_linear_shift", 
                                                h5("max_linear_shift"), 
                                                value = 0.05, step = 0.01)),
                            column(4, 
                                   numericInput("max_diff_peak2mean", 
                                                h5("max_diff_peak2mean"), 
                                                value = 0.03, step = 0.01)),
                            column(4, 
                                   numericInput("min_diff_peak2peak", 
                                                h5("min_diff_peak2peak"), 
                                                value = 0.03, step = 0.01)),
                            column(4,
                                   checkboxInput("delete_single_peak", "delete_single_peak", value = FALSE))),
                                   
                    fluidRow(
                    	     column(12, h4("ERah alignment parameters")),
                            column(4, 
                                   numericInput("min.spectra.cor", 
                                                h5("min.spectra.cor"), 
                                                value = 0.70, step = 0.01)),
                            column(4, 
                                   numericInput("max.time.dist", 
                                                h5("max_diff_peak2mean"), 
                                                value = 3, step = 0.1))),
                                  
                               
                                   
                    fluidRow(
                            column(12, h3("Peak annotation")),
                            column(12,
                                   checkboxInput("do_peak_annotation", "do_peak_annotation", value = TRUE)),
                            column(4, 
                                   numericInput("MinInt", 
                                                h5("MinInt"), 
                                                value = 20)),
                            column(4, 
                                   numericInput("MinMF", 
                                                h5("MinMF"), 
                                                value = 700)),
                            column(4, 
                                   numericInput("HITS", 
                                                h5("HITS"), 
                                                value = 10, step = 0.1))),
                    fluidRow(
                            column(8, h5("path_MSPepSearch"),
                                    actionButton("path to MSPepSearch","Select folder"),
                                    div(class="mt-n45", textInput("path_MSPepSearch_txt", "", value="/2019_02_22_MSPepSearch_x32/MSPepSearch.exe", placeholder = "../2019_02_22_MSPepSearch_x64/"))),
                            column(8, h5("path NIST MAIN library"),
                                   actionButton("path_MAIN","Select folder"),
                                   div(class="mt-n45", textInput("path_MAIN_txt", "", value="/var/log/shiny-server/NIST_library/mainlib", placeholder = "../NIST_library/mainlib"))),
                            column(8, h5("path to REPL library"),
                                   actionButton("path_REPL","Select folder"),
                                   div(class="mt-n45", textInput("path_REPL_txt", "", value="/var/log/shiny-server/NIST_library/replib", placeholder = "../NIST_library/replib")))),
                                   
                    fluidRow(
                            column(12, h3("Peak summary")),
                            column(12,
                                   checkboxInput("do_peak_summary", "do_peak_summary", value = TRUE)),
                            column(4, selectInput("select_name", h5("select_name"), 
                                                  choices = list("by_consensus" = "by_consensus", "by_MF" = "by_MF"))),                                   
                            column(8, h5("reference"),
                                   actionButton("reference","Select folder"),
                                   div(class="mt-n45", textInput("reference_sum", "",value="NULL", placeholder = "No directory has been selected")))),
                                
                    fluidRow(
                            column(12, 
                                   hr(class="lightcol"),
                                   div(class="text-right",
                                           actionButton("apply_gc", "Generate configuration file"),
                                           actionButton("reset", "Reset")))                         
                    )
       ),
       mainPanel(width = 8, h2("Output"),
                   div(id = "summary_box",verbatimTextOutput("summary", placeholder = TRUE)),
                 hidden(div(id = "graph_box",plotlyOutput("graph"))),
                 hidden(div(id = "coord_box",br(),verbatimTextOutput("coord_out"))),
                 div(id = "heatmap_box", 
                            fluidRow(plotlyOutput("heatmap", height = "800px"),
                                     hr(),dataTableOutput("heatmaptb"))
                 ),
                 br(),
                 div(class="text-right",
                     disabled(actionButton("proceed_gc", "Proceed")),
                     disabled(actionButton("submit_gc", "Submit job"))),
                 hidden(
                   div(id = "downloadgc_btn",
                       fluidRow(
                         column(12, hr()),
                         column(12, downloadButton("download_gc", "Download output"), actionButton("view_alignment", "View alignment"))
                       )
                   )
                 )
       )
))
